apiVersion: v1
kind: Namespace
metadata:
  name: argo-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: argo-nginx
  name: argo-nginx
  namespace: argo-demo
spec:
  replicas: 5
  selector:
    matchLabels:
      app: argo-nginx
  template:
    metadata:
      labels:
        app: argo-nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: argo-nginx
  namespace: argo-demo
spec:
  type: NodePort
  selector:
    app: argo-nginx
  ports:
  - port: 30000
    targetPort: 80


